environments:
    - name: dev
      configs:
        endpoints:
            production:
                url: 'http://backend-dev-service:8080/train-operations/v1/'
        deploymentEnvironments:
            - displayOnDevportal: true
              deploymentEnvironment: Default
              deploymentVhost : dev.gw.apim.com